package erp.utils;


public enum GroupBy {

    INVALID,

    DATE_DIRECT_ORDER,
    DATE_REVERSE_ORDER,
    DURATION_DIRECT_ORDER,
    DURATION_REVERSE_ORDER,
    DESCRIPTION_DIRECT_ORDER,
    DESCRIPTION_REVERSE_ORDER,
    REMOTE_FIRST,
    REMOTE_LAST
}
